# Generated by Django 5.0 on 2023-12-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PdfModel',
            new_name='Pdf',
        ),
    ]
